apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    tier: swoole-svc
data:
  config: |
    server {
      index index.php index.html;
      root /data/swoft;
      location / {
          proxy_pass http://swoole-svc.default.svc.cluster.local:80;
      }
    }
