apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: php-k8s
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-server
    servicePort: 80
  rules:
    - host: *
      http:
        paths:
          - path: /
            backend:
              serviceName: swoole-svc
              servicePort: 80
