apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: php-k8s-swoole
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "*.xswl.gq"
      http:
        paths:
          - path: /
            backend:
              serviceName: swoole-svc
              servicePort: 80