apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laravel-kubernetes-demo-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: default-http-server
    servicePort: 80
  rules:
    - host: "qq.xswl.gq"
      http:
        paths:
          - path: /
            backend:
              serviceName: swoole-svc
              servicePort: 80