apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: swoft-k8s
  name: php-k8s-swoole
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "*.xswl.gq"
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx
              servicePort: 80